title: Carl De Vries
url: "https://carldevries.com"
baseurl: ""

host: localhost
port: 4000

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/bk2dcradle"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

